name: Trigger auto deployment for container-app-duvtw6duuo5iy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-duvtw6duuo5iy-AutoDeployTrigger-2f5874d8-c476-42f8-b0d7-e374617ac402.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPDUVTW6DUUO5IY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPDUVTW6DUUO5IY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPDUVTW6DUUO5IY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPDUVTW6DUUO5IY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPDUVTW6DUUO5IY_REGISTRY_PASSWORD }}
          containerAppName: container-app-duvtw6duuo5iy
          resourceGroup: gptragdemoappspacebc5b
          imageToBuild: default/container-app-duvtw6duuo5iy:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


